### ISSUE TITLE
请教轮子哥关于CppMultiDimentionArray中array_size的设计

### ISSUE THREAD

**Issue by XiongKezhi** [vczh/vczh_toys#7]
最近我也在造一个N维数组的轮子，对于array_size这块儿，我是独立写的一个shape类(其实内部也就一个array用于存储每维度的信息)。想请教轮子哥为什么要使用这样的类似递归式的设计，而且在这样的设计当中，每次递归最底层的一层数据total都为1，好像没有什么实际的用途，那这样是不是浪费了一个int的空间呢。

**Comment by vczh** [comment]
细节已经不太记得了，总的来说array_size的递归是因为array本身是递归的，因为他要`operator[]`一直到完。至于如何去掉最后一个，我还没想要去怎么优化，不过应该是能做的。这么写主要是为了简化代码。
